import React from "react";
import Home from "../components/Home/Home";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <div>
      <Home />
    </div>
  );
};

export default HomePage;
